import { useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { AVAILABLE_SYNC_MODELS } from "../SyncEngine";

export function SyncModelSelector({ selected, available = AVAILABLE_SYNC_MODELS, onChange }: { selected: string[]; available?: string[]; onChange: (models: string[]) => void }) {
  const [search, setSearch] = useState("");
  const [custom, setCustom] = useState("");
  const visible = useMemo(() => [...new Set([...selected, ...available])].filter((model) => !search.trim() || model.toLowerCase().includes(search.trim().toLowerCase())).slice(0, 100), [available, search, selected]);
  function addCustom() { const model = custom.trim(); if (model && !selected.includes(model)) onChange([...selected, model]); setCustom(""); }
  return <View><Text style={styles.label}>MODEL ĐỒNG BỘ</Text><TextInput value={search} onChangeText={setSearch} placeholder="Tìm model đã tải từ Odoo…" autoCapitalize="none" style={styles.search} /><View style={styles.wrap}>{visible.map((model) => { const active = selected.includes(model); return <Pressable key={model} style={[styles.chip, active && styles.active]} onPress={() => onChange(active ? selected.filter((item) => item !== model) : [...selected, model])}><Text style={[styles.text, active && styles.activeText]}>{model}</Text></Pressable>; })}</View><View style={styles.customRow}><TextInput value={custom} onChangeText={setCustom} onSubmitEditing={addCustom} placeholder="Nhập model custom, ví dụ x_service.order" autoCapitalize="none" style={styles.customInput} /><Pressable style={styles.add} onPress={addCustom}><Text style={styles.addText}>Thêm</Text></Pressable></View>{available.length > 100 ? <Text style={styles.help}>Có {available.length} model remote. Dùng ô tìm kiếm để lọc.</Text> : null}</View>;
}

const styles = StyleSheet.create({ label: { color: "#857780", fontSize: 9, fontWeight: "900", letterSpacing: 0.8, marginBottom: 7 }, search: { height: 39, paddingHorizontal: 10, marginBottom: 8, borderWidth: 1, borderColor: "#DED6DB", borderRadius: 9, backgroundColor: "#FAF9F8", fontSize: 11 }, wrap: { flexDirection: "row", flexWrap: "wrap", gap: 6 }, chip: { paddingHorizontal: 9, paddingVertical: 7, borderWidth: 1, borderColor: "#DDD4DA", borderRadius: 9, backgroundColor: "#FFF" }, active: { borderColor: "#714B67", backgroundColor: "#EEE5EB" }, text: { color: "#766C73", fontSize: 9, fontWeight: "700" }, activeText: { color: "#714B67", fontWeight: "900" }, customRow: { flexDirection: "row", gap: 7, marginTop: 10 }, customInput: { flex: 1, height: 38, paddingHorizontal: 10, borderWidth: 1, borderColor: "#DED6DB", borderRadius: 9, fontSize: 10 }, add: { justifyContent: "center", paddingHorizontal: 13, borderRadius: 9, backgroundColor: "#714B67" }, addText: { color: "#FFF", fontSize: 10, fontWeight: "800" }, help: { color: "#92868D", fontSize: 8, marginTop: 7 } });
