import SQLite from "better-sqlite3";
import { spawnSync } from "node:child_process";

type Params = unknown[] | Record<string, unknown>;

export type DatabaseLike = {
  pragma(sql: string): void;
  prepare(sql: string): StatementLike;
  transaction<T extends (...args: any[]) => any>(fn: T): T;
};

export type StatementLike = {
  run(...params: unknown[]): { lastInsertRowid?: number | bigint; changes?: number };
  get(...params: unknown[]): unknown;
  all(...params: unknown[]): unknown[];
};

export function createDatabase(): DatabaseLike {
  const client = (process.env.DATABASE_CLIENT ?? "sqlite").toLowerCase();
  if (client === "postgres" || client === "postgresql") return new PostgresCliDatabase(process.env.DATABASE_URL);
  const sqlite = new SQLite(process.env.SQLITE_DATABASE_PATH ?? "record-platform.sqlite");
  return sqlite as unknown as DatabaseLike;
}

class PostgresCliDatabase implements DatabaseLike {
  constructor(private readonly url: string | undefined) {
    if (!url) throw new Error("DATABASE_URL is required when DATABASE_CLIENT=postgres");
    this.execute(`CREATE SCHEMA IF NOT EXISTS public`);
  }

  pragma(_sql: string) {
    // SQLite-only tuning hook.
  }

  prepare(sql: string): StatementLike {
    return new PostgresCliStatement(this, sql);
  }

  transaction<T extends (...args: any[]) => any>(fn: T): T {
    return ((...args: Parameters<T>) => fn(...args)) as T;
  }

  execute(sql: string) {
    const result = spawnSync("psql", [this.url!, "-X", "-q", "-v", "ON_ERROR_STOP=1", "-c", sql], { encoding: "utf8" });
    if (result.status !== 0) throw new Error(result.stderr || result.stdout || `psql exited with ${result.status}`);
  }

  query(sql: string) {
    const wrapped = `SELECT COALESCE(json_agg(row_to_json(t)), '[]'::json) FROM (${sql}) t`;
    return this.queryJson(wrapped);
  }

  queryJson(sql: string) {
    const result = spawnSync("psql", [this.url!, "-X", "-q", "-t", "-A", "-v", "ON_ERROR_STOP=1", "-c", sql], { encoding: "utf8", maxBuffer: 1024 * 1024 * 20 });
    if (result.status !== 0) throw new Error(result.stderr || result.stdout || `psql exited with ${result.status}`);
    const text = result.stdout.trim() || "[]";
    return JSON.parse(text) as unknown[];
  }
}

class PostgresCliStatement implements StatementLike {
  constructor(private readonly db: PostgresCliDatabase, private readonly sourceSql: string) {}

  run(...params: unknown[]) {
    const sql = this.render(params);
    if (isInsertReturningIdCandidate(sql)) {
      const rows = this.db.queryJson(`WITH inserted AS (${sql} RETURNING id) SELECT COALESCE(json_agg(row_to_json(inserted)), '[]'::json) FROM inserted`);
      return { lastInsertRowid: Number((rows[0] as any)?.id ?? 0), changes: rows.length };
    }
    this.db.execute(sql);
    return { changes: 0 };
  }

  get(...params: unknown[]) {
    return this.all(...params)[0];
  }

  all(...params: unknown[]) {
    const pragmaTable = parsePragmaTableInfo(this.sourceSql);
    if (pragmaTable) return this.tableInfo(pragmaTable);
    return this.db.query(this.render(params));
  }

  private render(params: unknown[]) {
    const values = normalizeParams(params);
    let position = 0;
    let sql = toPostgresSql(this.sourceSql);
    if (Array.isArray(values)) {
      sql = sql.replace(/\?/g, () => literal(values[position++]));
    } else {
      sql = sql.replace(/@([A-Za-z0-9_]+)/g, (_match, key) => literal(values[key]));
    }
    return sql;
  }

  private tableInfo(tableName: string) {
    return this.db.query(`
      SELECT column_name AS name
      FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = ${literal(unquoteIdent(tableName))}
      ORDER BY ordinal_position
    `);
  }
}

function normalizeParams(params: unknown[]): Params {
  if (params.length === 1 && isParamsObject(params[0])) return params[0] as Record<string, unknown>;
  return params;
}

function isParamsObject(value: unknown) {
  return Boolean(value && typeof value === "object" && !Array.isArray(value) && !Buffer.isBuffer(value));
}

function toPostgresSql(sql: string) {
  const hadInsertOrIgnore = /INSERT OR IGNORE INTO/i.test(sql);
  const translated = sql
    .replace(/INTEGER PRIMARY KEY AUTOINCREMENT/gi, "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    .replace(/INSERT OR IGNORE INTO/gi, "INSERT INTO")
    .replace(/\bLIKE\b/g, "ILIKE")
    .replace(/ON CONFLICT DO NOTHING\s*$/i, "ON CONFLICT DO NOTHING");
  return hadInsertOrIgnore && !/\bON\s+CONFLICT\b/i.test(translated) ? `${translated} ON CONFLICT DO NOTHING` : translated;
}

function parsePragmaTableInfo(sql: string) {
  const match = sql.match(/^\s*PRAGMA\s+table_info\((.+)\)\s*$/i);
  return match?.[1]?.trim();
}

function isInsertReturningIdCandidate(sql: string) {
  return /^\s*INSERT\s+INTO/i.test(sql) && !/\bON\s+CONFLICT\b/i.test(sql) && !/\bRETURNING\b/i.test(sql);
}

function literal(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number" || typeof value === "bigint") return String(value);
  if (typeof value === "boolean") return value ? "1" : "0";
  if (Buffer.isBuffer(value)) return `'\\x${value.toString("hex")}'`;
  const text = typeof value === "object" ? JSON.stringify(value) : String(value);
  return `'${text.replaceAll("'", "''")}'`;
}

function unquoteIdent(value: string) {
  return value.replace(/^"|"$/g, "").replaceAll('""', '"');
}
