import { Ionicons } from "@expo/vector-icons";
import { useEffect, useState } from "react";
import { KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import type { ModelValues } from "../../../core/types";
import { formatCurrency } from "../format";
import type { PosCartLine } from "../types";
import { PaymentMethodSelector } from "./PaymentMethodSelector";
import { PosCartLineItem } from "./PosCartLineItem";

export function PosCartModal({ visible, lines, methods, busy, lineTotal, onChangeLine, onRemoveLine, onClose, onCheckout }: { visible: boolean; lines: PosCartLine[]; methods: ModelValues[]; busy: boolean; lineTotal: (line: PosCartLine) => number; onChangeLine: (line: PosCartLine) => void; onRemoveLine: (key: string) => void; onClose: () => void; onCheckout: (paymentMethodId: string, customerName: string) => void }) {
  const [methodId, setMethodId] = useState("");
  const [customerName, setCustomerName] = useState("");
  useEffect(() => { if (visible) setMethodId((current) => current || methods[0]?.id as string || ""); }, [visible, methods]);
  const total = lines.reduce((sum, line) => sum + lineTotal(line), 0);
  return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.page}><View style={styles.header}><View><Text style={styles.overline}>ĐƠN HÀNG HIỆN TẠI</Text><Text style={styles.title}>Giỏ hàng · {lines.length} sản phẩm</Text></View><Pressable style={styles.close} onPress={onClose}><Ionicons name="close" size={22} color="#564C53" /></Pressable></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">{lines.length ? lines.map((line) => <PosCartLineItem key={line.key} line={line} total={lineTotal(line)} onChange={onChangeLine} onRemove={() => onRemoveLine(line.key)} />) : <View style={styles.empty}><Ionicons name="cart-outline" size={42} color="#A08F9A" /><Text style={styles.emptyText}>Chưa có sản phẩm trong giỏ</Text></View>}<View style={styles.customer}><Text style={styles.label}>KHÁCH HÀNG</Text><TextInput value={customerName} onChangeText={setCustomerName} placeholder="Khách lẻ" style={styles.customerInput} /></View><PaymentMethodSelector methods={methods} selectedId={methodId} onSelect={setMethodId} /></ScrollView><View style={styles.footer}><View><Text style={styles.totalLabel}>TỔNG THANH TOÁN</Text><Text style={styles.total}>{formatCurrency(total)}</Text></View><Pressable disabled={!lines.length || !methodId || busy} style={[styles.checkout, (!lines.length || !methodId || busy) && styles.disabled]} onPress={() => onCheckout(methodId, customerName)}><Text style={styles.checkoutText}>{busy ? "Đang xử lý…" : "Thanh toán"}</Text><Ionicons name="arrow-forward" size={18} color="#FFF" /></Pressable></View></KeyboardAvoidingView></Modal>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#F7F6F4" }, header: { paddingTop: 54, paddingHorizontal: 18, paddingBottom: 15, flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: "#FFF", borderBottomWidth: 1, borderBottomColor: "#E6E0E4" }, overline: { color: "#8D7786", fontSize: 9, fontWeight: "900", letterSpacing: 1 }, title: { color: "#342C32", fontSize: 22, fontWeight: "900", marginTop: 2 }, close: { width: 38, height: 38, borderRadius: 19, alignItems: "center", justifyContent: "center", backgroundColor: "#F1ECEF" }, content: { padding: 14, gap: 10, paddingBottom: 24 }, empty: { height: 170, alignItems: "center", justifyContent: "center", gap: 9 }, emptyText: { color: "#8D8189", fontSize: 13 }, customer: { gap: 6, marginTop: 5 }, label: { color: "#887E85", fontSize: 9, fontWeight: "900", letterSpacing: 0.8 }, customerInput: { height: 44, paddingHorizontal: 12, borderRadius: 11, borderWidth: 1, borderColor: "#D8D0D5", backgroundColor: "#FFF", color: "#3D353B" }, footer: { minHeight: 84, paddingHorizontal: 17, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 14, backgroundColor: "#FFF", borderTopWidth: 1, borderTopColor: "#E4DDE1" }, totalLabel: { color: "#8D8289", fontSize: 8, fontWeight: "900", letterSpacing: 0.8 }, total: { color: "#347553", fontSize: 20, fontWeight: "900", marginTop: 2 }, checkout: { height: 50, flexDirection: "row", alignItems: "center", gap: 7, paddingHorizontal: 20, borderRadius: 14, backgroundColor: "#714B67" }, disabled: { opacity: 0.45 }, checkoutText: { color: "#FFF", fontSize: 14, fontWeight: "900" } });
