import { Ionicons } from "@expo/vector-icons";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import type { PosCartLine } from "../types";
import { formatCurrency } from "../format";

export function PosCartLineItem({ line, total, onChange, onRemove }: { line: PosCartLine; total: number; onChange: (line: PosCartLine) => void; onRemove: () => void }) {
  return <View style={styles.card}><View style={styles.heading}><View style={styles.titleBox}><Text style={styles.name} numberOfLines={1}>{line.product.name}</Text><Text style={styles.code}>{line.product.defaultCode || "Sản phẩm"}</Text></View><Pressable style={styles.remove} onPress={onRemove}><Ionicons name="trash-outline" size={16} color="#B54747" /></Pressable></View><View style={styles.controls}><View><Text style={styles.label}>SỐ LƯỢNG</Text><View style={styles.qty}><Pressable style={styles.qtyButton} onPress={() => onChange({ ...line, qty: Math.max(0.01, line.qty - 1) })}><Ionicons name="remove" size={15} color="#714B67" /></Pressable><TextInput style={styles.qtyInput} keyboardType="decimal-pad" value={String(line.qty)} onChangeText={(value) => onChange({ ...line, qty: Math.max(0.01, Number(value) || 0.01) })} /><Pressable style={styles.qtyButton} onPress={() => onChange({ ...line, qty: line.qty + 1 })}><Ionicons name="add" size={15} color="#714B67" /></Pressable></View></View><View style={styles.inputGroup}><Text style={styles.label}>ĐƠN GIÁ</Text><TextInput style={styles.input} keyboardType="decimal-pad" value={String(line.priceUnit)} onChangeText={(value) => onChange({ ...line, priceUnit: Math.max(0, Number(value) || 0) })} /></View><View style={styles.discountGroup}><Text style={styles.label}>GIẢM %</Text><TextInput style={styles.discount} keyboardType="decimal-pad" value={String(line.discount)} onChangeText={(value) => onChange({ ...line, discount: Math.min(100, Math.max(0, Number(value) || 0)) })} /></View></View><View style={styles.totalRow}><Text style={styles.totalLabel}>Thành tiền</Text><Text style={styles.total}>{formatCurrency(total)}</Text></View></View>;
}

const styles = StyleSheet.create({ card: { padding: 13, borderRadius: 14, borderWidth: 1, borderColor: "#E5DFE3", backgroundColor: "#FFF", gap: 11 }, heading: { flexDirection: "row", alignItems: "center" }, titleBox: { flex: 1 }, name: { color: "#382F36", fontSize: 14, fontWeight: "800" }, code: { color: "#91868D", fontSize: 9, marginTop: 2 }, remove: { width: 30, height: 30, alignItems: "center", justifyContent: "center", borderRadius: 9, backgroundColor: "#FFF0F0" }, controls: { flexDirection: "row", alignItems: "flex-end", gap: 8 }, label: { color: "#968C93", fontSize: 8, fontWeight: "900", letterSpacing: 0.6, marginBottom: 4 }, qty: { height: 38, flexDirection: "row", alignItems: "center", borderWidth: 1, borderColor: "#D8D0D5", borderRadius: 10, overflow: "hidden" }, qtyButton: { width: 31, height: 38, alignItems: "center", justifyContent: "center", backgroundColor: "#F4EFF2" }, qtyInput: { width: 40, textAlign: "center", color: "#3F363D", fontWeight: "800" }, inputGroup: { flex: 1 }, input: { height: 38, minWidth: 85, paddingHorizontal: 9, borderWidth: 1, borderColor: "#D8D0D5", borderRadius: 10, color: "#3F363D", fontWeight: "700" }, discountGroup: { width: 58 }, discount: { height: 38, paddingHorizontal: 7, borderWidth: 1, borderColor: "#D8D0D5", borderRadius: 10, color: "#3F363D", textAlign: "center" }, totalRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop: 8, borderTopWidth: 1, borderTopColor: "#F0ECEF" }, totalLabel: { color: "#746A71", fontSize: 11 }, total: { color: "#347553", fontSize: 14, fontWeight: "900" } });
